package edu.dgut.mapper;

import edu.dgut.domain.PublicDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PublicDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pubbucket
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pubbucket
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    int insert(PublicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pubbucket
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    int insertSelective(PublicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pubbucket
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    PublicDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pubbucket
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    int updateByPrimaryKeySelective(PublicDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pubbucket
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    int updateByPrimaryKey(PublicDO record);

    List<PublicDO> getAll();


    List<PublicDO> getByPage(Integer pid);
}