package edu.dgut.mapper;

import edu.dgut.domain.RecordDO;

public interface RecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    int insert(RecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    int insertSelective(RecordDO record);
}