package edu.dgut.domain;

import java.io.Serializable;
import java.util.Date;

public class PublicDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pubbucket.id
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pubbucket.picture_name
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    private String pictureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pubbucket.create_time
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pubbucket.id
     *
     * @return the value of pubbucket.id
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pubbucket.id
     *
     * @param id the value for pubbucket.id
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pubbucket.picture_name
     *
     * @return the value of pubbucket.picture_name
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    public String getPictureName() {
        return pictureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pubbucket.picture_name
     *
     * @param pictureName the value for pubbucket.picture_name
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    public void setPictureName(String pictureName) {
        this.pictureName = pictureName == null ? null : pictureName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pubbucket.create_time
     *
     * @return the value of pubbucket.create_time
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pubbucket.create_time
     *
     * @param createTime the value for pubbucket.create_time
     *
     * @mbg.generated Sat Sep 12 15:44:26 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}