package edu.dgut.domain;

public class RecordDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.userName
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.devId
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    private String devid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.devName
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    private String devname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.finish
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    private String finish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.userName
     *
     * @return the value of record.userName
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.userName
     *
     * @param username the value for record.userName
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.devId
     *
     * @return the value of record.devId
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    public String getDevid() {
        return devid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.devId
     *
     * @param devid the value for record.devId
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    public void setDevid(String devid) {
        this.devid = devid == null ? null : devid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.devName
     *
     * @return the value of record.devName
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    public String getDevname() {
        return devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.devName
     *
     * @param devname the value for record.devName
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    public void setDevname(String devname) {
        this.devname = devname == null ? null : devname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.finish
     *
     * @return the value of record.finish
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    public String getFinish() {
        return finish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.finish
     *
     * @param finish the value for record.finish
     *
     * @mbg.generated Sat Sep 12 19:06:38 CST 2020
     */
    public void setFinish(String finish) {
        this.finish = finish == null ? null : finish.trim();
    }
}